name: Destroy DEV env

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

env:
  AWS_ROLE: 'arn:aws:iam::831947081981:role/JworksTechBlogGithubRole'

jobs:
  destroy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@a0de6af83968303c8c955486bf9739a57d23c7f1 # v1.10.0
        id: repository-token
        with:
          app-id: ${{ vars.ORDINA_GROUP_BOT_APP_ID }}
          private-key: ${{ secrets.ORDINA_GROUP_BOT_CERT }}
          owner: ${{ github.repository_owner }}
          repositories: "jworks-terraform-modules"

      - name: Checkout
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4

      - name: Setup git creds
        run: git config --global url."https://${{ vars.ORDINA_GROUP_BOT_APP_ID }}:${{ steps.repository-token.outputs.token }}@github".insteadOf https://github

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4.0.2
        with:
          role-to-assume: ${{ env.AWS_ROLE }}
          aws-region: eu-west-1

      - name: Remove files from s3
        run: aws s3 rm --recursive s3://blog.tst.ordina-jworks.io

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@651471c36a6092792c552e8b1bef71e592b462d8 # v3.1.1

      - name: Terraform Init
        id: init
        run: terraform init
        working-directory: infra/env/dev

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check
        working-directory: infra/env/dev

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
        working-directory: infra/env/dev

      - name: Terraform Plan Destroy
        id: plan-destroy
        run: terraform plan
        working-directory: infra/env/dev

      - name: Terraform Destroy
        id: destroy
        run: terraform destroy -auto-approve
        working-directory: infra/env/dev

